name: 'Git Changes'
description: 'Check if any uncommitted changes are found on the current state of your repo.'
author: 'Setare'
inputs:
  github_token:
    required: true
    description: 'Github token to access checks'
runs:
  using: 'node12'
  main: 'dist/index.js'
